name: Lighthouse

on:
  schedule:
    - cron:  '*/5 * * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  monitor:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Chrome
      run: sudo apt-get install chromium

    - name: Install Lighthouse
      run: npm install -g lighthouse
    
    - name: Running Lighthouse
      run: lighthouse --chrome-flags="--headless" "https://www.colbyfayock.com"
