name: Lighthouse

on: [push, pull_request]

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Uses Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install -g yarn
    - run: yarn install

    - name: Lighthouse Audit
      run: yarn lighthouse
      env:
        AUDIT_URL: "https://colbyfayock.com"

    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
