name: Lighthouse

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: colbyfayock/lighthouse-report-action@v2
      with:
        url: "https://colbyfayock.com/"
        outputDirectory: "test-reports"

    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
